### ISSUE TITLE
Payout calculation inconsistency 

### ISSUE THREAD

**Issue by xiaoyingpu** [MUCollective/vis-insight-reliability#1]
I just wrote some filtering to show the three trials where the payouts are inconsistent, i.e., the difference between the `cumulative_pay` is not the same as what is calculated from the reward formula 

https://github.com/MUCollective/vis-insight-reliability/blob/a1069978bba9791701bf613f3df6d3a4bc464658/pilot1/pilot_1.Rmd#L546-L564

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/8374573/74589822-c67e8f00-4fd6-11ea-8cf4-f812024d2979.png">

**Comment by abhsarma** [comment]
Interesting, the difference between the calculated and the value stored in the DB here is exactly the payout of the previous trial. Can't really say why that is happening.
