### ISSUE TITLE
Figure 4: Average FDR if B-H is used > 0.05?

### ISSUE THREAD

**Issue by xiaoyingpu** [MUCollective/vis-insight-reliability#3]
Some/all of these FDR's are greater than 0.05. B-H is supposed to control that but it's true that we only have one set of stimuli to calculate the average FDR so there can be uncertainty. Is there code somewhere that comes up with those FDR averages?

![image](https://user-images.githubusercontent.com/8374573/104738458-8c040180-5713-11eb-8d09-71d523217aed.png)

![image](https://user-images.githubusercontent.com/8374573/104738482-93c3a600-5713-11eb-97d1-371d6be2abf8.png)

My simulation code `p_value_payoffs_bh_ineq.Rmd` doesn't put the FDR average over 0.05 for B-H with our experiment stimuli data, so I wonder where the discrepancy is coming from (those facet columns (0.3, 0.45, etc) are mu/sigma ratios)

![image](https://user-images.githubusercontent.com/8374573/104741775-a2ac5780-5717-11eb-8963-16c02b738828.png)

**Comment by abhsarma** [comment]
The difference seems to be because of the metric you are calculating, which is FDR across all trials. What we did the analysis for is the average FDR for each trial, which is what I have plotted. Although there seems to be an error in the value I have as I used two-sided t-tests for calculating p-values, thanks for pointing it out.

I'll update the figures

**Comment by xiaoyingpu** [comment]
> The difference seems to be because of the metric you are calculating, which is FDR across all trials. What we did the analysis for is the average FDR for each trial, which is what I have plotted. Although there seems to be an error in the value I have as I used two-sided t-tests for calculating p-values, thanks for pointing it out.
> 
> I'll update the figures

I hope I'm calculating the average FDR within each trial, and that's averaged over all trials. 

https://github.com/MUCollective/vis-insight-reliability/blob/d9de824817b26b3da5c184077b21293a498e5ae8/src/p_value_payoffs_bh_ineq.Rmd#L430-L442

It'll be easier to just see your code; can you do a commit?

**Comment by abhsarma** [comment]
The calculation of FDR for each trial is here: https://github.com/MUCollective/vis-insight-reliability/blob/8db401e30c7612714614abbd828864a669628acc/R/analysis-final-study.Rmd#L306-L316

The BH calculation is here: https://github.com/MUCollective/vis-insight-reliability/blob/8db401e30c7612714614abbd828864a669628acc/R/stimuli-gen.Rmd#L132-L141

**Comment by xiaoyingpu** [comment]
- [x] Update figure with more correct FDR values for "uncorrected" and "BH", see #4
